# cupstestppd
# Autogenerated from man page /usr/share/man/man1/cupstestppd.1.gz
# using Deroffing man parser
complete -c cupstestppd -s I --description '. br Ignores all PCFileName warnings.'
complete -c cupstestppd -s R --description '.'
complete -c cupstestppd -s W --description '. br Report all UIConstraint errors as warnings.'
complete -c cupstestppd -s q --description '. br Specifies that no information should be displayed.'
complete -c cupstestppd -s r --description '.'
complete -c cupstestppd -s v --description '.'
complete -c cupstestppd -o vv --description '.'

