# git-prune-packed
# Autogenerated from man page /usr/share/man/man1/git-prune-packed.1
# using Deroffing man parser
complete -c git-prune-packed -s q -l quiet --description 'Squelch the progress indicator.'

