# git-pack-redundant
# Autogenerated from man page /usr/share/man/man1/git-pack-redundant.1
# using Deroffing man parser
complete -c git-pack-redundant -l verbose --description 'Outputs some statistics to stderr.'

