# git-for-each-ref
# Autogenerated from man page /usr/share/man/man1/git-for-each-ref.1
# using Deroffing man parser
complete -c git-for-each-ref -l format --description 'Subject: %(*subject) Date: %(*authordate) Ref: %(*refname).'

