# git-mergetool
# Autogenerated from man page /usr/share/man/man1/git-mergetool.1
# using Deroffing man parser
complete -c git-mergetool -l prompt --description 'Prompt before each invocation of the merge resolution program.'

