# git-mv
# Autogenerated from man page /usr/share/man/man1/git-mv.1
# using Deroffing man parser
complete -c git-mv -s n -l dry-run --description 'Do nothing; only show what would happen.'
complete -c git-mv -s v -l verbose --description 'Report the names of files as they are moved.'

