# git-submodule
# Autogenerated from man page /usr/share/man/man1/git-submodule.1
# using Deroffing man parser
complete -c git-submodule -l checkout --description 'to the command.  summary.'
complete -c git-submodule -l 'cached)' --description '.'
complete -c git-submodule -l submodule --description 'option with git-diff(1) will provide that information too.'
complete -c git-submodule -l shared --description 'options carefully.'

