# git-unpack-objects
# Autogenerated from man page /usr/share/man/man1/git-unpack-objects.1
# using Deroffing man parser
complete -c git-unpack-objects -l strict --description 'Don\\(cqt write objects with broken content or links.'

