# git-write-tree
# Autogenerated from man page /usr/share/man/man1/git-write-tree.1
# using Deroffing man parser
complete -c git-write-tree -l prefix --description 'Writes a tree object that represents a subdirectory <prefix>.'

