# h2ph5
# Autogenerated from man page /usr/share/man/man1/h2ph5.12.1.gz
# using Type1
complete -c h2ph5 -s a --description 'Run automagically; convert headerfiles, as well as any .'
complete -c h2ph5 -s l --description 'Symbolic links will be replicated in the destination directory.'
complete -c h2ph5 -s h --description 'Put ``hints\'\' in the .'
complete -c h2ph5 -s D --description 'Include the code from the . h file as a comment in the .'

