# xdpr
# Autogenerated from man page /usr/X11R6/share/man/man1/xdpr.1.gz
# using Deroffing man parser
complete -c xdpr -o device --description 'Specifies the device on which the file will be printed.'
complete -c xdpr -o help --description 'This option displays the list of options known to xdpr.'

