# xvinfo
# Autogenerated from man page /usr/X11R6/share/man/man1/xvinfo.1.gz
# using Deroffing man parser
complete -c xvinfo -o short --description 'Output less details, to reduce the amount of text.'

